# Configuración del servidor
server.port=8080

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cursos_db
spring.datasource.username=postgres
spring.datasource.password=secretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# --- Chaos Monkey Configuration ---
spring.profiles.active=chaos-monkey
chaos.monkey.enabled=true
chaos.monkey.watcher.restController=true
chaos.monkey.watcher.service=true
chaos.monkey.assaults.latencyActive=true
chaos.monkey.assaults.latencyRangeStart=500
chaos.monkey.assaults.latencyRangeEnd=2000
chaos.monkey.assaults.level=5