# Configuración del servidor
server.port=8080

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cursos_db
spring.datasource.username=postgres
spring.datasource.password=secretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Ver las consultas SQL a través del sistema de logging
logging.level.org.hibernate.SQL=DEBUG

# Ver los parámetros (valores reales) que se le pasan a los '?'
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Por esta nueva para Hibernate 6 (Spring Boot 3): Ver los parámetros (valores reales)
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Guarda todos los logs en un archivo llamado app.log en la raíz de tu proyecto
#logging.file.name=app.log


# --- Chaos Monkey Configuration ---
spring.profiles.active=chaos-monkey
chaos.monkey.enabled=false
chaos.monkey.watcher.restController=true
chaos.monkey.watcher.service=true
chaos.monkey.assaults.latencyActive=true
chaos.monkey.assaults.latencyRangeStart=500
chaos.monkey.assaults.latencyRangeEnd=2000
chaos.monkey.assaults.level=5

# Nombre y ruta del archivo de log actual --------
logging.file.name=logs/app.log

# Patrón para cuando el archivo "rote" (creará archivos tipo app-2026-09-13.0.log, etc.)
logging.logback.rollingpolicy.file-name-pattern=logs/app-%d{yyyy-MM-dd}.%i.log

# Tamaño máximo que puede alcanzar un archivo antes de rotar (ej: 10 MB)
logging.logback.rollingpolicy.max-file-size=10MB

# Cuántos días hacia atrás se guardan los logs antiguos (ej: 30 días)
logging.logback.rollingpolicy.max-history=30

# Límite total de espacio que pueden ocupar todos los logs juntos (ej: 3 GB)
# Si se pasa de 3GB, empieza a borrar los más antiguos automáticamente
logging.logback.rollingpolicy.total-size-cap=3GB


logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [traceId=%X{traceId}, spanId=%X{spanId}] - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [traceId=%X{traceId}, spanId=%X{spanId}] - %msg%n

# Convierta el formato RFC 9457 - Exceptions
spring.mvc.problemdetails.enabled=true
