<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.curso</groupId>
		<artifactId>multimodulo-capas</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>application</artifactId>

	<dependencies>
		<!-- Solo necesitamos la implementación, que ya arrastra todo lo demás -->
		<dependency>
			<groupId>com.curso</groupId>
			<artifactId>service-impl</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>com.curso</groupId>
			<artifactId>dto</artifactId>
			<version>${project.version}</version>
		</dependency>

		<!-- Starter web para levantar la aplicación como una API REST -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>com.curso</groupId>
			<artifactId>domain-usuarios</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>chaos-monkey-spring-boot</artifactId>
			<!-- Asegúrate de usar una versión compatible con tu Spring Boot,
			ej: 3.x o 2.x -->
			<version>3.1.0</version> <!-- (O la última versión acorde a tu Spring
			Boot) -->
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<!-- Los trace ID-->
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-tracing-bridge-brave</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<parameters>true</parameters>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>